version: '3'

services:
  portal-frontend:
    image: nginx:1.17.8-alpine
    container_name: portal-frontend
    restart: unless-stopped
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./dist/portal-front:/usr/share/nginx/html
    networks:
      - observatorio-network
networks:
  observatorio-network:
    external:
      name: observatorio-network
